[tool.poetry]
name = "qr-code"
version = "0.1.0"
description = ""
authors = ["radik <radikmanasyan@gmail.com>"]

package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
qrcode = {extras = ["pil"], version = "^7.4.2"}
